name: BUG
description: 버그 수정
labels: ["bug"]
body:
  - type: dropdown
    id: application
    attributes:
      label: 애플리케이션
      options:
        - Utils
        - hook
        - page
        - component
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 버그 설명 및 수정 내용
      placeholder: 어떤 버그였는지 / 어떻게 수정했는지
    validations:
      required: true

  - type: textarea
    id: test
    attributes:
      label: 테스트
      placeholder: 버그가 수정되었는지 어떻게 확인했는지 설명해주세요
    validations:
      required: true
