name: ENHANCEMENT
description: 기능 개선
labels: ["enhancement"]
body:
  - type: dropdown
    id: application
    attributes:
      label: 애플리케이션
      options:
        - Utils
        - hook
        - page
        - component
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 개선 내용
      placeholder: 현재 상황 / 개선 방안 / 변경 사항
    validations:
      required: true

  - type: textarea
    id: test
    attributes:
      label: 테스트
      placeholder: 어떻게 테스트했는지 설명해주세요
    validations:
      required: true
