name: TASK
description: 기타 작업
labels: ["task"]
body:
  - type: dropdown
    id: application
    attributes:
      label: 애플리케이션
      options:
        - Utils
        - hook
        - page
        - component
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 작업 내용
      placeholder: 어떤 작업을 수행했는지 / 작업 이유
    validations:
      required: true
