name: BUG
description: 버그 리포트
title: "[BUG] "
labels: ["bug"]
body:
  - type: dropdown
    id: application
    attributes:
      label: 애플리케이션
      options:
        - Utils
        - hook
        - page
        - component
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 내용
      placeholder: 버그 설명 / 재현 방법 / 예상 동작
    validations:
      required: true
