name: ENHANCEMENT
description: 기능 개선
title: "[ENHANCEMENT] "
labels: ["enhancement"]
body:
  - type: dropdown
    id: application
    attributes:
      label: 애플리케이션
      options:
        - xquare-user-application
        - Utils
        - hook
        - page
        - component
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 내용
      placeholder: 현재 상황 / 개선 방안
    validations:
      required: true
